site_name: Jacob MKdoc Test
site_description: "这是一个mkdocs的demo测试知识网站"
site_author: "Jacob Xi"
copyright: "Copyright &copy; 2016-2020 Jacob Xi"

nav:
  - 主页: "index.md"
  - 关于: "about.md"
  - 自动化: "devops.md"

repo_url: https://github.com/Chao-Xi/mkdocstest.git
repo_name: "Opening on Github"

theme: 
  language: zh
  name: 'material'
  include_sidebar: true
  logo: 'images/logo.png'
  feature:
    tabs: false
  palette:
    primary: 'amber'
    accent: 'amber'
  i18n:
    prev: 'Previous'
    next: 'Next'



